trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'  

variables:
  appName: 'NewWebAppDotNETArs'  # Replace with your Azure App Service name
  azureSubscription: 'Mindtree Poland DEV (e504bc3f-d3d7-4548-81ce-692a4fe7ff93)'
  gitHubRepository: 'https://github.com/ArslanTem/WebApp.NET'  
  environmentName: 'production'
  branchName: 'master'

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '7.x'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        MaxArtifactSize: 1
    - task: AzureRmWebAppDeployment@4
      inputs:
       ConnectionType: 'AzureRM'
       azureSubscription: 'Mindtree Poland DEV (e504bc3f-d3d7-4548-81ce-692a4fe7ff93)'
       appType: 'webApp'
       WebAppName: 'NewWebAppDotNETArs'
       packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
       enableCustomDeployment: true
       DeploymentType: 'webDeploy'