trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'  

variables:
  appName: 'NewWebAppDotNETArs'  # Replace with your Azure App Service name
  azureSubscription: 'Mindtree Poland DEV'  # Replace with your Azure subscription name
  gitHubRepo: 'https://github.com/ArslanTem/WebApp.NET'  # Replace with your GitHub repository URL
  environmentName: 'production'  # Replace with the name of your deployment environment

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '7.x'

    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        package: $(Pipeline.Workspace)/drop/**/*.zip
        deploymentMethod: 'zipDeploy'
        enableCustomDeployment: true
        deploymentSlots: 'Production'  # Replace with the deployment slot name if used
